import os

REDDIT_CLIENT=os.getenv('REDDIT_CLIENT')
REDDIT_SECRET=os.getenv('REDDIT_SECRET')
REDDIT_USERNAME=os.getenv('REDDIT_USERNAME')
REDDIT_PASSWORD=os.getenv('REDDIT_PASSWORD')

PG_USER=os.getenv('REDDIT_MURMUR_PG_USER')
PG_PW=os.getenv('REDDIT_MURMUR_PG_PW')
PG_DB=os.getenv('REDDIT_MURMUR_DB')
